Repository fine-ants/FineAnts, pull requests merged in 2023-11, with the labels that each got.

#104 [feat] 포트폴리오 상세 조회시 배당금 데이터를 응답하도록 구현
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHolding.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/stock/Stock.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/stock_dividend/StockDividend.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/stock_dividend/StockDividendRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisMessageController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/manager/CurrentPriceManager.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortFolioCreateResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_gain_history/PortfolioGainHistoryService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioDetailResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioHoldingDetailItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/StockDividendItem.java
  fineAnts_app/src/main/resources/db/mysql/data.sql
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio/PortfolioTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/member/service/MemberServiceTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioRestControllerTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioHoldingRestControllerTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockServiceTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_stock/response/PurchaseHistoryItemTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryRestControllerTest.java
Labels: backend, feat

#102 [refactor] portfolioOverView 리팩토링
  fe/src/api/portfolio/index.ts
  fe/src/api/portfolio/queries/queryKeys.ts
  fe/src/api/portfolio/queries/usePortfolioAddMutation.ts
  fe/src/api/portfolio/queries/usePortfolioDeleteMutation.ts
  fe/src/api/portfolio/queries/usePortfolioEditMutation.ts
  fe/src/components/Portfolio/PortfolioModal.tsx
  fe/src/components/Portfolio/PortfolioOverview.tsx
  fe/src/components/ToggleSwitch.tsx
  fe/src/mocks/data/portfolioData.ts
  fe/src/mocks/data/portfolioDetailsData.ts
  fe/src/mocks/handlers/portfolioHandlers.ts
  fe/src/utils/calculations.ts
Labels: frontend, refactor

#109 [feat] 포트폴리오 매입 이력 추가 및 수정 기능 구현
  fe/package-lock.json
  fe/package.json
  fe/src/api/portfolio/index.ts
  fe/src/components/BaseModal.tsx
  fe/src/components/Portfolio/PortfolioHoldingRow.tsx
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingAddModal.tsx
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingLotRow.tsx
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingLots.tsx
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingPurchaseAddModal.tsx
  fe/src/components/Portfolio/PortfolioHoldingsTable.tsx
  fe/src/main.tsx
  fe/src/mocks/data/portfolioData.ts
  fe/src/mocks/handlers/portfolioHandlers.ts
  fe/src/pages/PortfolioPage.tsx
Labels: frontend, feat

#110 [feat] 목표수익금액/최대손실금액 알림 서비스 구현
  fineAnts_app/build.gradle
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/PortfolioRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/aop/AccessTokenAspect.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/client/KisClient.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/manager/CurrentPriceManager.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/response/CurrentPriceResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/request/PortfolioCreateRequest.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortfoliosResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_gain_history/PortfolioGainHistoryService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_notification/MailService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_notification/PortfolioNotificationRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_notification/PortfolioNotificationService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_notification/request/PortfolioNotificationModifyRequest.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_notification/response/PortfolioNotificationModifyResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/success/code/PortfolioSuccessCode.java
  fineAnts_app/src/main/resources/application.yml
  fineAnts_app/src/main/resources/db/mysql/data.sql
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/kis/KisServiceTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/member/service/MemberServiceTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_gain_history/PortfolioGainHistoryServiceTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_notification/MailServiceTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_notification/PortfolioNotificationRestControllerTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_notification/PortfolioNotificationServiceTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioHoldingServiceTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockServiceTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryServiceTest.java
Labels: backend, feat

#112 [fix] 코드 충돌 해결
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/manager/CurrentPriceManager.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockServiceTest.java
Labels: backend, bug

#117 [fix] @EnableWebMvc 제거
  fineAnts_app/src/main/java/codesquad/fineants/spring/config/WebConfig.java
Labels: backend, bug

#122 [fix] 브로드캐스팅 문제 해결
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisService.java
Labels: backend, bug

#123 [feat] StockPage 구현 및 포트폴리오 종목 추가,삭제 구현
  fe/src/api/auth/queries/useSignUpMutation.ts
  fe/src/api/portfolio/index.ts
  fe/src/api/portfolio/queries/usePortfolioHoldingAddMutation.ts
  fe/src/api/portfolio/queries/usePortfolioHoldingDeleteMutation.ts
  fe/src/api/portfolio/queries/usePortfolioListQuery.ts
  fe/src/api/stock/index.ts
  fe/src/assets/images/Toss_Symbol_Primary.png
  fe/src/components/Dashboard/PortfolioPieChart.tsx
  fe/src/components/Portfolio/DividendBarChart.tsx
  fe/src/components/Portfolio/HoldingsPieChart.tsx
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingAddModal.tsx
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingRow.tsx
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingsTable.tsx
  fe/src/components/Portfolio/PortfolioOverview.tsx
  fe/src/components/Portfolio/SectorBar.tsx
  fe/src/components/SearchBar.tsx
  fe/src/components/SearchBar/SearchBar.tsx
  fe/src/components/SearchBar/SearchItem.tsx
  fe/src/components/TradingViewWidgets/TVStockDetailWidget.tsx
  fe/src/components/common/Header.tsx
  fe/src/mocks/handlers/portfolioHandlers.ts
  fe/src/mocks/handlers/stockHandlers.ts
  fe/src/pages/PortfolioPage.tsx
  fe/src/pages/StockPage.tsx
Labels: frontend, feat, design

#124 [feat] 포트폴리오 상세 조회 및 종목 조회 WebSocket 구현
  fe/package-lock.json
  fe/package.json
  fe/src/api/auth/index.ts
  fe/src/api/auth/queries/useSignOutMutation.ts
  fe/src/api/hooks/useStompSubWithRQ.tsx
  fe/src/api/portfolio/queries/usePortfolioAddMutation.ts
  fe/src/components/Portfolio/PortfolioModal.tsx
  fe/src/components/Portfolio/PortfolioOverview.tsx
  fe/src/components/hooks/useText.tsx
  fe/src/constants/config.ts
  fe/src/pages/PortfolioPage.tsx
  fe/src/pages/ProfilePage/ProfileEditPage.tsx
  fe/src/pages/SignInPage.tsx
  fe/src/pages/SignUpPage/subPages/EmailSubPage.tsx
  fe/src/pages/SignUpPage/subPages/NicknameSubPage.tsx
  fe/src/pages/SignUpPage/subPages/PasswordSubPage.tsx
Labels: frontend, feat, refactor

#127 [merge] 잔버그 수정
  fe/src/api/portfolio/queries/usePortfolioEditMutation.ts
  fe/src/components/Portfolio/PortfolioOverview.tsx
  fe/src/pages/PortfolioPage.tsx
Labels: frontend, fix

#128 [merge] 잔 버그 수정
  fe/src/api/portfolio/queries/usePortfolioEditMutation.ts
  fe/src/components/Portfolio/PortfolioOverview.tsx
  fe/src/pages/PortfolioPage.tsx
Labels: frontend, merge

#130 [refactor] 비동기 예외 설정
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/manager/CurrentPriceManager.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/kis/KisMessageControllerTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockServiceTest.java
Labels: backend

#133 [merge] LandingPage 구현 및 배포 위한 잔버그 수정
  fe/src/api/portfolio/queries/usePortfolioHoldingAddMutation.ts
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingAddModal.tsx
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingRow.tsx
  fe/src/components/common/Header.tsx
  fe/src/pages/LandingPage.tsx
  fe/src/pages/PortfolioPage.tsx
  fe/src/router/router.tsx
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisMessageController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/client/KisClient.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/manager/CurrentPriceManager.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/manager/PortfolioSubscriptionManager.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_gain_history/PortfolioGainHistoryService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioDetailResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioHoldingsResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/ws/portfolio/PortfolioMessageController.java
  fineAnts_app/src/main/resources/ssl/keystore.p12
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryServiceRepositoryTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_notification/PortfolioNotificationServiceTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockServiceTest.java
Labels: frontend, merge

#137 [feat] 변동값 색깔 구분되게 구현
  fe/src/api/portfolio/index.ts
  fe/src/components/Dashboard/PortfolioPieChart.tsx
  fe/src/components/Portfolio/DividendBarChart.tsx
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingRow.tsx
  fe/src/components/Portfolio/PortfolioOverview.tsx
  fe/src/pages/ProfilePage/PortfoliosPage.tsx
Labels: frontend, feat, design

#138 [merge] 데모 전 배포를 위한 공유
  README.md
  fe/src/api/portfolio/index.ts
  fe/src/components/Dashboard/PortfolioPieChart.tsx
  fe/src/components/Portfolio/DividendBarChart.tsx
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingRow.tsx
  fe/src/components/Portfolio/PortfolioOverview.tsx
  fe/src/pages/ProfilePage/PortfoliosPage.tsx
  fineAnts_app/docker-compose-dev.yml
Labels: frontend, merge

#139 [style] 속성값 변경 후 적용
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingRow.tsx
  fe/src/pages/ProfilePage/PortfoliosPage.tsx
Labels: frontend, style
