Repository fine-ants/FineAnts, pull requests merged in 2023-10, with the labels that each got.

#12 [feat] 스프링 서버 프로젝트 초기화
  .gitignore
  .idea/.gitignore
  .idea/checkstyle-idea.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/stock_n_go.iml
  .idea/vcs.xml
  docs/API 진행 상황.md
  docs/BE/기술 스택.md
  docs/스크럽.md
  docs/회의안.md
  fineAnts_app/.gitignore
  fineAnts_app/build.gradle
  fineAnts_app/gradle/wrapper/gradle-wrapper.jar
  fineAnts_app/gradle/wrapper/gradle-wrapper.properties
  fineAnts_app/gradlew
  fineAnts_app/gradlew.bat
  fineAnts_app/settings.gradle
  fineAnts_app/src/main/java/codesquad/fineants/FineAntsAppApplication.java
  fineAnts_app/src/main/resources/application.properties
  fineAnts_app/src/test/java/codesquad/fineants/FineAntsAppApplicationTests.java
Labels: backend

#13 [feat] Home/Dashboard 구현
  fe/src/components/NavBar.tsx
  fe/src/components/SearchBar.tsx
  fe/src/components/TradingViewWidgets/TVTickerTape.tsx
  fe/src/components/common/Dropdown.tsx
  fe/src/components/common/Footer.tsx
  fe/src/components/common/Header.tsx
  fe/src/components/common/UserControls.tsx
  fe/src/pages/DashboardPage.tsx
Labels: frontend, feat, design

#26 [feat] SignUpPage 구현
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/api/auth/index.ts
  fe/src/api/auth/queries/useOAuthSignInMutation.ts
  fe/src/api/auth/queries/useSignUpMutation.ts
  fe/src/components/VerificationCodeInput/VerificationCodeInput.tsx
  fe/src/index.css
  fe/src/main.tsx
  fe/src/pages/BasePage.tsx
  fe/src/pages/SignUpPage.tsx
  fe/src/pages/SignUpPage/SignUpPage.tsx
  fe/src/pages/SignUpPage/subPages/EmailSubPage.tsx
  fe/src/pages/SignUpPage/subPages/MainSubPage.tsx
  fe/src/pages/SignUpPage/subPages/NicknameSubPage.tsx
  fe/src/pages/SignUpPage/subPages/PasswordSubPage.tsx
  fe/src/pages/SignUpPage/subPages/SubPage.tsx
  fe/src/pages/SignUpPage/subPages/VerificationSubPage.tsx
  fe/src/pages/SignUpPage/subPages/index.ts
  fe/src/router/ProtectedRoute.tsx
  fe/src/router/PublicOnlyRoute.tsx
  fe/src/router/Routes.ts
  fe/src/router/router.tsx
  fe/src/styles/GlobalStyles.tsx
  fe/tsconfig.json
  fe/vite.config.ts
Labels: frontend, feat

#29 [feat] 한국 투자증권 open api 연결
  fineAnts_app/build.gradle
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisMessageController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/client/AES256.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/client/KisWebSocketClientEndpoint.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/client/OauthKisClient.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/properties/OauthKisProperties.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/response/KisRealTimeSigningPriceResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/response/OauthKisApprovalResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/config/OauthConfig.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/config/WebSocketConfig.java
  fineAnts_app/src/main/resources/static/app.js
  fineAnts_app/src/main/resources/static/index.html
  fineAnts_app/src/main/resources/stocks.csv
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/kis/client/OauthKisClientTest.java
Labels: backend, feat

#27 [feat] my profile page 구현
  fe/src/pages/ProfilePage/MyProfilePage.tsx
  fe/src/pages/ProfilePage/PortfoliosPage.tsx
  fe/src/pages/ProfilePage/ProfileEditPage.tsx
  fe/src/router/Routes.ts
  fe/src/router/router.tsx
  fe/src/utils/addComma.ts
  fe/vite.config.ts
Labels: frontend, feat

#28 [feat] WatchlistPage 구현
  fe/package-lock.json
  fe/package.json
  fe/src/components/NavBar.tsx
  fe/src/components/TradingViewWidgets/TVTickerTape.tsx
  fe/src/components/Watchlist/Watchlist.tsx
  fe/src/components/Watchlist/WatchlistItem.tsx
  fe/src/components/common/Header.tsx
  fe/src/pages/WatchlistPage.tsx
Labels: frontend, feat, design

#32 [feat] 포트폴리오 추가 서비스 구현
  fineAnts_app/src/main/java/codesquad/fineants/FineAntsAppApplication.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/PortfolioRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/stock/Stock.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/errors/errorcode/PortfolioErrorCode.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/errors/handler/GlobalExceptionHandler.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/client/KisWebSocketClientEndpoint.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/request/PortfolioCreateRequest.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortFolioCreateResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/response/ApiResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/config/JpaAuditingConfiguration.java
  fineAnts_app/src/main/resources/db/mysql/data.sql
  fineAnts_app/src/main/resources/stocks.tsv
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/kis/client/OauthKisClientTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioRestControllerTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java
Labels: backend, feat

#33 [feat] 포트폴리오 수정 및 삭제 서비스 구현
  fineAnts_app/src/main/java/codesquad/fineants/domain/BaseEntity.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/PortfolioRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_stock/PortFolioStock.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_stock/PortFolioStockRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/trade_history/TradeHistory.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/trade_history/TradeHistoryRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/errors/errorcode/PortfolioErrorCode.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/client/AES256.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/response/KisRealTimeSigningPriceResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/request/PortfolioModifyRequest.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortFolioItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortfolioListResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortfolioModifyResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/success/code/PortfolioSuccessCode.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioRestControllerTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java
Labels: backend, feat

#35 [feat] CI/CD 설정
  .github/workflows/cicd.yml
  fineAnts_app/appspec.yml
  fineAnts_app/scripts/deploy.sh
Labels: docs

#37 [feat] 포트폴리오 목록 조회 구현
  fineAnts_app/build.gradle
  fineAnts_app/src/main/java/codesquad/fineants/domain/page/ScrollPaginationCollection.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/PortfolioPaginationRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/PortfolioRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistory.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_stock/PortFolioStock.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/stock/Market.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/stock/Stock.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/stock_dividend/StockDividend.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/trade_history/TradeHistory.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/request/PortfolioCreateRequest.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/request/PortfolioModifyRequest.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortFolioItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortfolioListResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortfoliosResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/success/code/PortfolioSuccessCode.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/config/QuerydslConfiguration.java
  fineAnts_app/src/main/resources/stocks.csv
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio/PortfolioTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryRepositoryTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_stock/PortFolioStockTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/trade_history/TradeHistoryTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioRestControllerTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java
Labels: backend, feat

#38 [feat] 포트폴리오 목록 조회 구현
  .github/workflows/cicd.yml
  fineAnts_app/appspec.yml
  fineAnts_app/build.gradle
  fineAnts_app/scripts/deploy.sh
  fineAnts_app/src/main/java/codesquad/fineants/FineAntsAppApplication.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/BaseEntity.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/page/ScrollPaginationCollection.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/PortfolioPaginationRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/PortfolioRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistory.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_stock/PortFolioStock.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_stock/PortFolioStockRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/stock/Market.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/stock/Stock.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/stock_dividend/StockDividend.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/trade_history/TradeHistory.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/trade_history/TradeHistoryRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/errors/errorcode/PortfolioErrorCode.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/errors/handler/GlobalExceptionHandler.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/client/AES256.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/client/KisWebSocketClientEndpoint.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/response/KisRealTimeSigningPriceResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/request/PortfolioCreateRequest.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/request/PortfolioModifyRequest.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortFolioCreateResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortFolioItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortfolioModifyResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortfoliosResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/response/ApiResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/success/code/PortfolioSuccessCode.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/config/JpaAuditingConfiguration.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/config/QuerydslConfiguration.java
  fineAnts_app/src/main/resources/db/mysql/data.sql
  fineAnts_app/src/main/resources/stocks.csv
  fineAnts_app/src/main/resources/stocks.tsv
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio/PortfolioTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryRepositoryTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_stock/PortFolioStockTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/trade_history/TradeHistoryTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/kis/client/OauthKisClientTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioRestControllerTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java
Labels: backend

#34 [feat] Dashboard 포트폴리오 파이차트, 총 자산현황 라인차트 구현
  fe/package-lock.json
  fe/package.json
  fe/src/api/portfolio/index.ts
  fe/src/api/portfolio/queries/queryKeys.ts
  fe/src/api/portfolio/queries/usePortfolioChartQuery.ts
  fe/src/components/Dashboard/PortfolioOverview.tsx
  fe/src/components/Dashboard/PortfolioPieChart.tsx
  fe/src/components/Dashboard/TimeRangeButton.tsx
  fe/src/components/Dashboard/TotalValueLineChart.tsx
  fe/src/components/Watchlist/WatchlistItem.tsx
  fe/src/components/common/Dropdown.tsx
  fe/src/components/common/Header.tsx
  fe/src/components/common/PieChart/Legend.tsx
  fe/src/components/common/PieChart/LegendItem.tsx
  fe/src/components/common/PieChart/RechartPieChart.tsx
  fe/src/mocks/data/portfolioData.ts
  fe/src/mocks/handlers/index.ts
  fe/src/mocks/handlers/portfolioHandlers.ts
  fe/src/pages/DashboardPage.tsx
Labels: frontend, feat, design

#43 [feat] 포트폴리오 종목 추가 및 삭제 서비스 구현
  fineAnts_app/build.gradle
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_stock/PortFolioStockRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_stock/PortfolioStock.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/stock/StockRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/trade_history/TradeHistory.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/trade_history/TradeHistoryRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/errors/errorcode/PortfolioStockErrorCode.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/errors/errorcode/StockErrorCode.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/errors/handler/GlobalExceptionHandler.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortfoliosResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/request/PortfolioStockCreateRequest.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockCreateResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockDeleteResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/success/code/PortfolioStockSuccessCode.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/success/code/PortfolioSuccessCode.java
  fineAnts_app/src/main/resources/db/mysql/data.sql
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio/PortfolioTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_stock/PortfolioStockTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/trade_history/TradeHistoryTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestControllerTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockServiceTest.java
Labels: backend, feat

#42 [feat] OAuth SignIn 구현
  fe/index.html
  fe/package-lock.json
  fe/package.json
  fe/src/api/auth/index.ts
  fe/src/api/auth/queries/useOAuthSignInMutation.ts
  fe/src/api/fetcher.ts
  fe/src/assets/images/kakao_login_medium_narrow.png
  fe/src/assets/images/kakao_login_medium_wide.png
  fe/src/components/auth/GoogleSignInButton.tsx
  fe/src/components/auth/KakaoSignInButton.tsx
  fe/src/components/auth/NaverSignInButton.tsx
  fe/src/constants/config.ts
  fe/src/context/WindowContext.tsx
  fe/src/hooks/useText.tsx
  fe/src/mocks/browserServiceWorker.ts
  fe/src/mocks/data/authData.ts
  fe/src/mocks/handlers/authHandlers.ts
  fe/src/mocks/handlers/index.ts
  fe/src/pages/SignInPage.tsx
  fe/src/pages/SignUpPage/SignUpPage.tsx
  fe/src/pages/SignUpPage/subPages/EmailSubPage.tsx
  fe/src/pages/SignUpPage/subPages/MainSubPage.tsx
  fe/src/pages/SignUpPage/subPages/NicknameSubPage.tsx
  fe/src/pages/SignUpPage/subPages/PasswordSubPage.tsx
  fe/src/pages/SignUpPage/subPages/VerificationSubPage.tsx
  fe/src/router/router.tsx
  fe/src/utils/openPopUpWindow.ts
  fe/tsconfig.json
Labels: frontend, feat

#45 [feat] 종목 검색 구현
  fineAnts_app/build.gradle
  fineAnts_app/docker-compose.yml
  fineAnts_app/src/main/java/codesquad/fineants/elasticsearch/configuration/ElasticSearchConfig.java
  fineAnts_app/src/main/java/codesquad/fineants/elasticsearch/controller/StockSearchController.java
  fineAnts_app/src/main/java/codesquad/fineants/elasticsearch/document/StockSearch.java
  fineAnts_app/src/main/java/codesquad/fineants/elasticsearch/helper/Indices.java
  fineAnts_app/src/main/java/codesquad/fineants/elasticsearch/helper/Util.java
  fineAnts_app/src/main/java/codesquad/fineants/elasticsearch/repository/StockSearchRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/elasticsearch/search/SearchRequestDTO.java
  fineAnts_app/src/main/java/codesquad/fineants/elasticsearch/search/util/SearchUtil.java
  fineAnts_app/src/main/java/codesquad/fineants/elasticsearch/service/ElasticSearchService.java
  fineAnts_app/src/main/java/codesquad/fineants/elasticsearch/service/StockService.java
  fineAnts_app/src/main/java/codesquad/fineants/elasticsearch/service/response/StockSearchItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioDetailResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockDetailItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStocksResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/StockItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/TradeHistoryItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/success/code/PortfolioStockSuccessCode.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/success/code/StockSuccessCode.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/config/JpaConfig.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/filter/JwtAuthorizationFilter.java
  fineAnts_app/src/main/resources/application.yml
  fineAnts_app/src/main/resources/static/es-settings.json
  fineAnts_app/src/main/resources/stocks.tsv
  fineAnts_app/src/test/java/codesquad/fineants/elasticsearch/service/ElasticSearchServiceTest.java
Labels: backend, feat

#48 [feat] 포스트맨 변경 사항 반영
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_stock/PortFolioStockRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_stock/PortfolioHolding.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_stock/PortfolioStock.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/trade_history/TradeHistory.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/trade_history/TradeHistoryRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortFolioItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockCreateResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockDeleteResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockDetailItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStocksResponse.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio/PortfolioTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_stock/PortFolioStockTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_stock/PortfolioHoldingTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioHoldingRestControllerTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioHoldingServiceTest.java
Labels: backend, feat

#49 [feat] 포트폴리오 종목 조회 구현
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_stock/PortFolioHoldingRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_stock/PortFolioStockRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_stock/PortfolioHolding.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortFolioItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioDetailResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioHoldingDetailItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioHoldingsResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockDetailItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockItem.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio/PortfolioTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_stock/PortfolioHoldingTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioHoldingServiceTest.java
Labels: backend, feat

#53 PortfolioPage API 공유를 위한 PR
  fe/package-lock.json
  fe/package.json
  fe/src/api/portfolio/index.ts
  fe/src/api/portfolio/queries/queryKeys.ts
  fe/src/api/portfolio/queries/usePortfolioDetailsQuery.ts
  fe/src/assets/icons/plus.svg
  fe/src/components/Portfolio/PortfolioHoldingRow.tsx
  fe/src/components/Portfolio/PortfolioHoldingsTable.tsx
  fe/src/mocks/data/portfolioData.ts
  fe/src/mocks/handlers/portfolioHandlers.ts
  fe/src/pages/PortfolioPage.tsx
  fe/src/router/Routes.ts
  fe/src/router/router.tsx
Labels: frontend, feat, merge

#56 [fix] 포스트맨 변경 사항 반영
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_holding/PortFolioHoldingRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHolding.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/purchase_history/PurchaseHistory.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/purchase_history/PurchaseHistoryRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/stock/Stock.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/stock/StockRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/trade_history/TradeHistoryRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/request/PortfolioStockCreateRequest.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioHoldingDetailItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioHoldingsResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockCreateResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PurchaseHistory.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/StockItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/stock/response/StockSearchItem.java
  fineAnts_app/src/main/resources/db/mysql/data.sql
  fineAnts_app/src/main/resources/stocks.tsv
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio/PortfolioTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_holding/PortfolioHoldingTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/purchase_history/PurchaseHistoryTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioHoldingRestControllerTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioHoldingServiceTest.java
Labels: backend, fix

#57 [fix] 포스트맨 변경 사항 반영
  .github/workflows/cicd.yml
  fineAnts_app/Dockerfile
  fineAnts_app/build.gradle
  fineAnts_app/docker-compose-dev.yml
  fineAnts_app/docker-compose.yml
  fineAnts_app/scripts/deploy.sh
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_holding/PortFolioHoldingRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHolding.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_stock/PortFolioStock.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_stock/PortFolioStockRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/purchase_history/PurchaseHistory.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/purchase_history/PurchaseHistoryRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/stock/Stock.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/stock/StockRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/trade_history/TradeHistoryRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/errors/errorcode/PortfolioStockErrorCode.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/errors/errorcode/StockErrorCode.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/errors/handler/GlobalExceptionHandler.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortFolioItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortfoliosResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/request/PortfolioStockCreateRequest.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioDetailResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioHoldingDetailItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioHoldingsResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockCreateResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockDeleteResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PurchaseHistory.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/StockItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/stock/StockRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/stock/StockService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/stock/request/StockSearchRequest.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/stock/response/StockSearchItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/success/code/PortfolioStockSuccessCode.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/success/code/PortfolioSuccessCode.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/success/code/StockSuccessCode.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/filter/JwtAuthorizationFilter.java
  fineAnts_app/src/main/resources/application.yml
  fineAnts_app/src/main/resources/db/mysql/data.sql
  fineAnts_app/src/main/resources/stocks.tsv
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio/PortfolioTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_holding/PortfolioHoldingTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_stock/PortFolioStockTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/purchase_history/PurchaseHistoryTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioHoldingRestControllerTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioHoldingServiceTest.java
Labels: backend, fix

#58 [feat] 매입 이력 추가 서비스 구현
  fineAnts_app/src/main/java/codesquad/fineants/domain/purchase_history/PurchaseHistory.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/errors/errorcode/PortfolioHoldingErrorCode.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/request/PurchaseHistoryCreateRequest.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/response/PurchaseHistoryCreateResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/success/code/PurchaseHistorySuccessCode.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio/PortfolioTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryRepositoryTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_holding/PortfolioHoldingTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/purchase_history/PurchaseHistoryTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryRestControllerTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryServiceTest.java
Labels: backend, feat

#59 Dependencies 공유를 위한 PR
  fe/__tests__/utils/date.test.ts
  fe/package-lock.json
  fe/package.json
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingLots.tsx
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingRow.tsx
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingsTable.tsx
  fe/src/pages/PortfolioPage.tsx
  fe/src/utils/date.ts
Labels: frontend, chore, merge

#61 [feat] 매입 이력 수정 및 삭제 서비스 구현
  fineAnts_app/src/main/java/codesquad/fineants/domain/purchase_history/PurchaseHistory.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/errors/errorcode/PurchaseHistoryErrorCode.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PurchaseHistoryItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/request/PurchaseHistoryModifyRequest.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/response/PurchaseHistoryDeleteResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/response/PurchaseHistoryModifyResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/success/code/PurchaseHistorySuccessCode.java
  fineAnts_app/src/main/resources/db/mysql/data.sql
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryRestControllerTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryServiceTest.java
Labels: backend, feat

#63 [fix] 포트폴리오 목록 조회 버그 수정
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortFolioItem.java
Labels: backend, fix

#64 [fix] 포트폴리오 목록 조회 응답 수정
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_stock/PortFolioStock.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/purchase_history/PurchaseHistory.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/errors/errorcode/PortfolioHoldingErrorCode.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/errors/errorcode/PurchaseHistoryErrorCode.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortFolioItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortfolioListResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PurchaseHistoryItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/request/PurchaseHistoryCreateRequest.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/request/PurchaseHistoryModifyRequest.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/response/PurchaseHistoryCreateResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/response/PurchaseHistoryDeleteResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/response/PurchaseHistoryModifyResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/success/code/PurchaseHistorySuccessCode.java
  fineAnts_app/src/main/resources/db/mysql/data.sql
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio/PortfolioTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryRepositoryTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_holding/PortfolioHoldingTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/purchase_history/PurchaseHistoryTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryRestControllerTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryServiceTest.java
Labels: backend, fix

#65 [feat] 포트폴리오 손익 내역 기록 서비스 구현
  fineAnts_app/docker-compose-dev.yml
  fineAnts_app/scripts/deploy.sh
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistory.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHolding.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortfoliosResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_gain_history/PortfolioGainHistoryService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_gain_history/response/PortfolioGainHistoryCreateResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/config/SpringConfig.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio/PortfolioTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryRepositoryTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryServiceRepositoryTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_holding/PortfolioHoldingTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_gain_history/PortfolioGainHistoryServiceTest.java
Labels: backend, feat

#67 [feat] 포트폴리오 수익 내역 추가 서비스 구현
  fineAnts_app/docker-compose-dev.yml
  fineAnts_app/scripts/deploy.sh
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistory.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryRepository.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHolding.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortfoliosResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_gain_history/PortfolioGainHistoryService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_gain_history/response/PortfolioGainHistoryCreateResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioDetailResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/config/SpringConfig.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio/PortfolioTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryServiceRepositoryTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_holding/PortfolioHoldingTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_gain_history/PortfolioGainHistoryServiceTest.java
Labels: backend, feat

#69 [feat] 매입 내역 목록 조회 구현
  fineAnts_app/src/main/java/codesquad/fineants/domain/purchase_history/PurchaseHistory.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PurchaseHistory.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PurchaseHistoryItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/request/PurchaseHistoryCreateRequest.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/request/PurchaseHistoryModifyRequest.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/response/PurchaseHistoryModifyResponse.java
  fineAnts_app/src/main/resources/db/mysql/data.sql
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio/PortfolioTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryRepositoryTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_holding/PortfolioHoldingTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/purchase_history/PurchaseHistoryTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_gain_history/PortfolioGainHistoryServiceTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioHoldingServiceTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_stock/response/PurchaseHistoryItemTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryRestControllerTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryServiceTest.java
Labels: backend, feat

#70 [fix] 포트폴리오 상세 조회시 손익 공식 개선
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHolding.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/purchase_history/PurchaseHistory.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioDetailResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PurchaseHistory.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PurchaseHistoryItem.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/request/PurchaseHistoryCreateRequest.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/request/PurchaseHistoryModifyRequest.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/purchase_history/response/PurchaseHistoryModifyResponse.java
  fineAnts_app/src/main/resources/db/mysql/data.sql
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio/PortfolioTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryRepositoryTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/portfolio_holding/PortfolioHoldingTest.java
  fineAnts_app/src/test/java/codesquad/fineants/domain/purchase_history/PurchaseHistoryTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_gain_history/PortfolioGainHistoryServiceTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioHoldingServiceTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/portfolio_stock/response/PurchaseHistoryItemTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryRestControllerTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryServiceTest.java
Labels: backend, feat, fix

#71 [feat] 포트폴리오 종목 테이블 관련 기능 중간 공유
  fe/package.json
  fe/src/api/auth/queries/useSignInMutation.ts
  fe/src/api/auth/queries/useSignOutMutation.ts
  fe/src/api/portfolio/index.ts
  fe/src/api/portfolio/queries/queryKeys.ts
  fe/src/api/portfolio/queries/usePortfolioHoldingAddMutation.ts
  fe/src/api/portfolio/queries/usePortfolioHoldingDeleteMutation.ts
  fe/src/api/portfolio/queries/usePortfolioHoldingPurchaseAddMutation.ts
  fe/src/api/portfolio/queries/usePortfolioHoldingPurchaseDeleteMutation.ts
  fe/src/api/portfolio/queries/usePortfolioHoldingPurchaseEditMutation.ts
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingLotRow.tsx
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingLots.tsx
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingRow.tsx
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingsTable.tsx
  fe/src/pages/PortfolioPage.tsx
  fe/src/pages/ProfilePage/ProfileEditPage.tsx
  fe/src/pages/SignInPage.tsx
  fe/src/pages/SignUpPage/subPages/EmailSubPage.tsx
  fe/src/pages/SignUpPage/subPages/NicknameSubPage.tsx
  fe/src/pages/SignUpPage/subPages/PasswordSubPage.tsx
  fe/src/utils/authInputValidators.ts
  fe/src/utils/date.ts
Labels: frontend, feat, merge

#72 [feat] 포트폴리오 상태 영역 구현 및 공용 컴포넌트 구현
  fe/package-lock.json
  fe/package.json
  fe/src/api/portfolio/index.ts
  fe/src/components/BaseModal.tsx
  fe/src/components/ConfirmAlert.tsx
  fe/src/components/Portfolio/PortfolioModal.tsx
  fe/src/components/Portfolio/PortfolioOverview.tsx
  fe/src/components/ToggleSwitch.tsx
  fe/src/main.tsx
  fe/src/mocks/data/portfolioData.ts
  fe/src/pages/PortfolioPage.tsx
  fe/vite.config.ts
Labels: frontend, feat, rename, add

#79 [refactor] kis 서버 액세스 토큰 발급 만료 문제 해결
  fineAnts_app/build.gradle
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHolding.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisMessageController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisRedisService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/aop/AccessTokenAspect.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/client/KisClient.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/client/KisWebSocketClientEndpoint.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/manager/KisAccessTokenManager.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/config/SpringConfig.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/config/WebSocketConfig.java
  fineAnts_app/src/main/resources/db/mysql/data.sql
  fineAnts_app/src/main/resources/static/app.js
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/kis/KisServiceTest.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/kis/manager/KisAccessTokenManagerTest.java
Labels: backend, feat, refactor

#81 [fix] 주식 현재가가 0인 경우 비동기적으로 수행되는 문제 해결
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisClientScheduler.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/aop/AccessTokenAspect.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/client/KisClient.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/ws/portfolio/PortfolioMessageController.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/kis/KisServiceTest.java
Labels: bug

#82 [fix] 주식 현재가가 0인 경우 비동기적으로 수행되는 문제 해결
  fineAnts_app/src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisClientScheduler.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/aop/AccessTokenAspect.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/client/KisClient.java
  fineAnts_app/src/test/java/codesquad/fineants/spring/api/kis/KisServiceTest.java
Labels: bug

#86 [Fix] Build error 수정
  fe/src/components/Dashboard/ValuationOverview.tsx
  fe/src/components/Portfolio/PortfolioOverview.tsx
  fe/src/pages/DashboardPage.tsx
Labels: frontend, fix, merge

#87 [Fix] FE Build error 수정
  fe/src/components/Dashboard/ValuationOverview.tsx
  fe/src/components/Portfolio/PortfolioOverview.tsx
  fe/src/pages/DashboardPage.tsx
Labels: frontend, fix, merge

#88 [fix] 포트폴리오 목록 조회 및 상세 조회 수정
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisStompEventListener.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortfoliosResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PurchaseHistoryItem.java
Labels: backend, bug

#89 [fix] 포트폴리오 목록 조회 및 상세 조회 수정 (#88)
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisStompEventListener.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortfoliosResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PurchaseHistoryItem.java
Labels: backend, bug

#90 [fix] cors 설정 추가
  fineAnts_app/scripts/deploy.sh
  fineAnts_app/src/main/java/codesquad/fineants/spring/config/WebConfig.java
Labels: backend, bug

#91 [feat] Portfolio holding purchase history 삭제 기능
  fe/package-lock.json
  fe/package.json
  fe/src/api/portfolio/index.ts
  fe/src/api/portfolio/queries/usePortfolioHoldingAddMutation.ts
  fe/src/api/portfolio/queries/usePortfolioHoldingDeleteMutation.ts
  fe/src/api/portfolio/queries/usePortfolioHoldingPurchaseAddMutation.ts
  fe/src/api/portfolio/queries/usePortfolioHoldingPurchaseDeleteMutation.ts
  fe/src/api/portfolio/queries/usePortfolioHoldingPurchaseEditMutation.ts
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingLotRow.tsx
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingLots.tsx
  fe/src/components/Portfolio/PortfolioHoldings/PortfolioHoldingRow.tsx
  fe/src/main.tsx
  fe/src/mocks/data/portfolioData.ts
  fe/src/mocks/handlers/portfolioHandlers.ts
Labels: frontend, feat

#94 [feat] 클라이언트 스톰프 연결 종료시 포트폴리오 구독 제거 구현
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisMessageController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/StockPriceManager.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/interceptor/KisWebSocketInterceptor.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/listener/KisStompEventListener.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/request/MessageData.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortfoliosResponse.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PurchaseHistoryItem.java
Labels: backend, feat

#95 [feat] 클라이언트 스톰프 연결 종료시 포트폴리오 구독 제거 구현
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisMessageController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/KisService.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/StockPriceManager.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/interceptor/KisWebSocketInterceptor.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/listener/KisStompEventListener.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/kis/request/MessageData.java
Labels: backend, feat

#99 [feat] 포트폴리오 추가시 응답으로 portfolioId 응답하도록 구현
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioRestController.java
  fineAnts_app/src/main/java/codesquad/fineants/spring/api/portfolio/response/PortFolioCreateResponse.java
Labels: backend, feat

#96 [feat] 검색바 UI에 검색 API 연동
  fe/.eslintrc.cjs
  fe/package-lock.json
  fe/src/api/stock/index.ts
  fe/src/api/stock/queries/queryKeys.ts
  fe/src/api/stock/queries/useStockSearchQuery.ts
  fe/src/components/Dashboard/PortfolioOverview.tsx
  fe/src/components/Dashboard/TotalValuationLineChart.tsx
  fe/src/components/Portfolio/DividendBarChart.tsx
  fe/src/components/Portfolio/HoldingsPieChart.tsx
  fe/src/components/Portfolio/PortfolioHoldingAddModal.tsx
  fe/src/components/Portfolio/SectorBar.tsx
  fe/src/components/SearchBar.tsx
  fe/src/components/TradingViewWidgets/TVTickerTape.tsx
  fe/src/components/Watchlist/Watchlist.tsx
  fe/src/components/auth/NaverSignInButton.tsx
  fe/src/components/common/Dropdown.tsx
  fe/src/components/common/Footer.tsx
  fe/src/components/common/Header.tsx
  fe/src/components/common/PieChart/RechartPieChart.tsx
  fe/src/hooks/useText.tsx
  fe/src/mocks/data/stockData.ts
  fe/src/mocks/handlers/index.ts
  fe/src/mocks/handlers/stockHandlers.ts
  fe/src/pages/BasePage.tsx
  fe/src/pages/DashboardPage.tsx
  fe/src/pages/PortfolioPage.tsx
  fe/src/pages/ProfilePage/ProfileEditPage.tsx
Labels: feat
